name: Release

on:
  push:
    tags:
      - v**.**

jobs:
  # GNU/Linux AMD64 (x86-64)
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v3

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc make sed grep wget gawk tar \
            gcc-x86-64-linux-gnu

      - name: "Build static openssl"
        run: |
          CC="x86_64-linux-gnu-gcc" \
          LD="x86_64-linux-gnu-ld" \
          AS="x86_64-linux-gnu-as" \
          C_INCLUDE_PATH="/usr/include/x86_64-linux-gnu/" \
          LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/" \
            ./scripts/openssl.sh linux-x86_64

      - name: "Build static curl"
        run: |
          CC="x86_64-linux-gnu-gcc" \
          LD="x86_64-linux-gnu-ld" \
          AS="x86_64-linux-gnu-as" \
          C_INCLUDE_PATH="/usr/include/x86_64-linux-gnu/" \
          LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/" \
            ./scripts/curl.sh x86_64-pc-linux-gnu

      - name: "Build the static binaries"
        run: |
          CC="x86_64-linux-gnu-gcc" \
          LD="x86_64-linux-gnu-ld" \
          AS="x86_64-linux-gnu-as" \
          C_INCLUDE_PATH="/usr/include/x86_64-linux-gnu/" \
          LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/" \
            ./scripts/build.sh -static

      - name: "Upload the binaries"
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64
          path: |
            dist/encryptor
            dist/decryptor

  # GNU/Linux i386 (IA-32)
  linux-i386:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v3

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc make sed grep wget gawk tar \
            gcc-i686-linux-gnu

      - name: "Build static openssl"
        run: |
          CC="i686-linux-gnu-gcc" \
          LD="i686-linux-gnu-ld"  \
          AS="i686-linux-gnu-as"  \
          C_INCLUDE_PATH="/usr/i686-linux-gnu/include/" \
          LIBRARY_PATH="/usr/i686-linux-gnu/lib/:/usr/lib/gcc-cross/i686-linux-gnu/13/" \
            ./scripts/openssl.sh linux-x86

      - name: "Build static curl"
        run: |
          CC="i686-linux-gnu-gcc -m32" \
          LD="i686-linux-gnu-ld"       \
          AS="i686-linux-gnu-as"       \
          C_INCLUDE_PATH="/usr/i686-linux-gnu/include/" \
          LIBRARY_PATH="/usr/i686-linux-gnu/lib/:/usr/lib/gcc-cross/i686-linux-gnu/13/" \
            ./scripts/curl.sh i386-pc-linux-gnu

      - name: "Build the static binaries"
        run: |
          CC="i686-linux-gnu-gcc" \
          LD="i686-linux-gnu-ld"  \
          AS="i686-linux-gnu-as"  \
          C_INCLUDE_PATH="/usr/i686-linux-gnu/include/" \
          LIBRARY_PATH="/usr/i686-linux-gnu/lib/:/usr/lib/gcc-cross/i686-linux-gnu/13/" \
            ./scripts/build.sh -static -m32

      - name: "Upload the binaries"
        uses: actions/upload-artifact@v4
        with:
          name: linux-i386
          path: |
            dist/encryptor
            dist/decryptor

  # publish the release
  publish:
    runs-on: ubuntu-latest
    needs:
      - linux-amd64
      - linux-i386
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v3

      - name: "Download linux-amd64 binaries"
        uses: actions/download-artifact@v4
        with:
          name: linux-amd64

      - name: "Setup linux-amd64 archive"
        run: |
          name="lokpack-${{github.ref_name}}-linux-amd64"
          mkdir -v "${name}"
          mv -v encryptor decryptor "${name}"
          cp -v scripts/patch.py "${name}"
          tar czvf "${name}.tar.gz" "${name}"

      - name: "Download linux-i386 binaries"
        uses: actions/download-artifact@v4
        with:
          name: linux-i386

      - name: "Setup linux-i386 archive"
        run: |
          name="lokpack-${{github.ref_name}}-linux-i386"
          mkdir -v "${name}"
          mv -v encryptor decryptor "${name}"
          cp -v scripts/patch.py "${name}"
          tar czvf "${name}.tar.gz" "${name}"

      - name: "Create release"
        id: create_release
        uses: actions/create-release@v1 # WARN: this is unmaintained
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: lokpack ${{github.ref}}
          body: |
            Please see the README file for instructions for using the automated
            binary builds

      - name: "Upload linux-amd64 archive"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: lokpack-${{github.ref_name}}-linux-amd64.tar.gz
          asset_name: lokpack-${{github.ref_name}}-linux-amd64.tar.gz

      - name: "Upload linux-i386 archive"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: lokpack-${{github.ref_name}}-linux-i386.tar.gz
          asset_name: lokpack-${{github.ref_name}}-linux-i386.tar.gz
